# ESPHome Node settings
esphome:
  name: atmo-test
  comment: testing configuration for atmospheric measurements, temperature and humidity
  friendly_name: atmo-test

# ESPHome Processor settings
esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

#ESPHome Enable logging
logger:
  level: INFO

# OTA update settings
ota:
  password: !secret ota_password

  # Automation on start
  on_begin:
    then:
      - logger.log: "OTA start"

  # Automation during upload
  on_progress:
    then:
      - logger.log:
          format: "OTA progress %0.1f%%"
          args: ["x"]

  # Automation on end
  on_end:
    then:
      - logger.log: "OTA end"

  # Automation on error
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]

# Wifi settings
wifi:
  # Credentials
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # IP settings
  manual_ip:
    static_ip: 192.168.1.75
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

  # Wifi-fallback settings for access point
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

# ESPHome Captive Portal settings
captive_portal:

# ESPHome MQTT settings
mqtt:
  # Credentials
  broker: !secret mqtt_broker # Broker IP
  username: !secret mqtt_username # Broker username
  password: !secret mqtt_password # Broker password

  # Topic to post on-connect
  birth_message:
    topic: atmo-test/status
    payload: online

  # Topic to post on-disconnect
  will_message:
    topic: atmo-test/status
    payload: offline

i2c:
      sda: GPIO21
      scl: GPIO22
      scan: true
      id: bus_a

# ESPHome sensors
sensor:
  - platform: sgp4x
    id: air_quality_sensor
    i2c_id: bus_a
    address: 0x59
    voc:
      name: "VOC Index"
      id: voc_index
    compensation:
      humidity_source: dht22_hum
      temperature_source: dht22_temp

  - platform: dht
    model: DHT22_TYPE2
    pin: GPIO32
    temperature:
      name: "temperature"
      id: dht22_temp
    humidity:
      name: "humidity"
      id: dht22_hum
    update_interval: 60s